version: '3'

services:

  # Database Service
  database:
    image: database
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: examplePassword  
      MONGO_INITDB_DATABASE: reaDYP_users
    ports:
      - "27017:27017"

  # Frontend Service
  frontend:
    image: frontend
    ports:
      - "8888:80"
    depends_on:
      - backend

  # Backend Service
  backend:
    image: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
